### PR TITLE
Hot fix for 1.12 support.

### PR DESCRIPTION
**Pull request by k-jiang**
It just a simple fix for supporting Bukkit / Spigot 1.12 due to changes of APIs. This fix will not work with 1.11 or lower, though you can still add some version detection into ConfigAccessor.java for backward compability.

### CODE REVIEW

**Comment by k-jiang** [comment]
credit to https://github.com/Abrasam/HyperMerchant/commit/203a2da3ee258a0d8c3b8519c3a9867d1eeafbec

**Comment by PikaMug** [comment]
@k-jiang All for the update, but could you elaborate on why this breaks compatibility with 1.11? Maybe I'm blind but I don't see any classes named "ConfigAccessor" either.

**Comment by k-jiang** [comment]
I'm sorry that message was a mistake. I copied it from other plugins :p there were so many like this.

In version 1.12, `YamlConfiguration.loadConfiguration()` is changed to take `InputStreamReader` instead of `InputStream`. If you want to have backward compatibility, a simple solution is you could modify your src/main/java/grokswell/util/MenuButtonData.java and src/main/java/grokswell/util/Blacklist.java, feed the `loadConfiguration()` method with different types of Stream according to craftbukkit version. Noticed that there should be no error while build no matter what version of spigot/craftbukkit you have in pom.xml.

But to be honest, I'm not a pro. I believe there should be some other nice decent way to do it, just not within my knowledge.

**Comment by PikaMug** [comment]
@k-jiang Ah okay, but `InputStreamReader` is a subclass of `Reader`, and `YamlConfiguration.loadConfiguration()` has accepted that since at least Bukkit 1.7.10 ([source](https://jd.bukkit.org/org/bukkit/configuration/file/YamlConfiguration.html)).

I was also guilty of ignoring the `InputStream` deprecation in Quests. An alternative would be to just use `saveResource("npcblacklist.yml", false)` but the end result is the same.

@remremrem @RegalOwl Looking forward to this merge <3

**Comment by remremrem** [comment]
Thank you very much for contributing to the development of HyperMerchant. 
I have merged the near identical commit by Abrasam since it was submitted first. I would merge your pom.xml file but I don't know of a simple way to cherry pick a single file, so I will edit that file by hand.
Thanks again!

**Pull request closed without merging**
